default:
  image: mrkobhrai/node14-firebase-tools:latest

stages:
  - Style Check
  - Install Dependencies
  - Build Frontend
  - Deploy

frontend-style-check:
  stage: Style Check
  script:
    - cd react-frontend
    - eslint .

backend-style-check:
  stage: Style Check
  script:
    - cd functions
    - eslint .
  
frontend-dependencies:
  stage: Install Dependencies
  script:
    - cd react-frontend
    - npm ci
  cache:
    untracked: true
    key: "$CI_COMMIT_BRANCH-frontend"
    paths:
      - react-frontend/node_modules/
  artifacts:
    paths:
      - react-frontend/node_modules/
  needs: ["frontend-style-check"]

backend-dependencies:
  stage: Install Dependencies
  script:
    - cd functions
    - npm ci
  cache:
    untracked: true
    key: "$CI_COMMIT_BRANCH-backend"
    paths:
      - functions/node_modules/
  artifacts:
    paths:
      - functions/node_modules/
  needs: ["backend-style-check"]
  
build-frontend:
  stage: Build Frontend
  script:
    - cd react-frontend
    - npm run build
  artifacts:
    paths:
      - react-frontend/build
  needs: ["frontend-dependencies"]

deploy-frontend:
  stage: Deploy
  script:
    - firebase deploy --only hosting --token "${FIREBASE_DEPLOY_TOKEN}"
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
  needs: ["build-frontend", "backend-dependencies"]

deploy-backend:
  stage: Deploy
  script:
    - firebase deploy --only functions --token "${FIREBASE_DEPLOY_TOKEN}"
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
  needs: ["build-frontend", "backend-dependencies"]



